services:
  - type: web
    name: cyberprotocol-fiambreria
    runtime: docker
    region: oregon
    branch: produccion
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://cyberprotocol-fiambreria.onrender.com
      - key: ASSET_URL
        value: https://cyberprotocol-fiambreria.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_LEVEL
        value: warning
      - key: SESSION_ENCRYPT
        value: true
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: es
      - key: APP_FAKER_LOCALE
        value: es_ES
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
